# Funding

We encourage organizations to provide funding to support our ongoing research and development efforts.

- [Open Research Development Laboratories](https://ordl.org) - Your contributions can help us enhance our projects and support innovation.