FROM node:22-alpine
WORKDIR /app
COPY ordl_platform/frontend/package*.json ./
RUN npm install
COPY ordl_platform/frontend .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
