FROM registry.access.redhat.com/ubi9/openjdk-21:latest
USER root
RUN dnf install -y --nodocs libseccomp && dnf clean all
RUN useradd -m -s /bin/bash -u 1000 sandbox && mkdir -p /sandbox && chown -R sandbox:sandbox /sandbox
USER sandbox
WORKDIR /sandbox
ENTRYPOINT ["java"]
CMD ["--version"]
